### ISSUE TITLE
Expected release date?

### ISSUE THREAD

**Issue by shreyaspurohit** [mongodb/mongo-scala-driver#3]
We are using mongo and would be nice if there is an estimate of the release so that we can plan ahead. Thanks.

**Comment by rozza** [comment]
Currently this is still going through some development.  A Beta is due out next week and then we'll solicit feedback on the API from users before aiming to have a release candidate out by the end of the quarter.

**Comment by shreyaspurohit** [comment]
cool, thanks for the update!

**Comment by dbuschman7** [comment]
Awesome!

**Comment by rozza** [comment]
FYI - I now consider the SNAPSHOT to be stable.  We are reliant on the unreleased 3.1 Java driver which is also available via a SNAPSHOT

**Comment by dbuschman7** [comment]
If the 'beta" for this driver is due next week, does that infer that the Java 3.1.x driver will also release a numbered version as well?

**Comment by rozza** [comment]
Sorry, a large refactoring and shading of namespaces delayed the beta. The Java driver release is expected next quarter and this driver will follow on from that.

**Comment by rozza** [comment]
I'm pleased to announce the first release candidate is available!

You can find more information on the documentation site:  http://mongodb.github.io/mongo-scala-driver/

**Comment by hepin1989** [comment]
finally,what a nice.
