### ISSUE TITLE
Scala macro to auto-generate Codecs from case classes

### ISSUE THREAD

**Issue by dbuschman7** [mongodb/mongo-scala-driver#6]
Are there any plans to add a Scala macro to register Codecs generated from Scala case classes?

**Comment by joiskov** [comment]
+1

**Comment by rozza** [comment]
This is something that is definitely on the roadmap - [SCALA-168](https://jira.mongodb.org/browse/SCALA-168) just haven't been able to scheduled the development time.

I'd appreciate any ideas, thoughts or inputs on it.  

For instance would Macro Annotations from macro paradise be a good idea or would having to also include it at compile time to use it put you off?

**Comment by dbuschman7** [comment]
I would like to see if a "straight" macro would work since the library is only being built for 2.11 and not 2.10; no cross version compatibly issues with 2.10. I have a task for work coming up that might require a macro, I can play around a bit and see what insights come from that effort.

**Comment by alek-sys** [comment]
Hi, I'm doing some prototyping now, to see where it can get. If you are interested - code available here https://github.com/alek-sys/mongodb-codec

The idea is to do a macro to generate codec by case class definition in compile time. Like
```scala
case class User(name: String, age: Int)
val codec = MongoCodecProvider.getCodec[User]()
```
Still a lot to do, like nested case classes, optional types etc, but looks like idea might work quite good.

**Comment by rozza** [comment]
Thanks all - will follow up in [SCALA-168](https://jira.mongodb.org/browse/SCALA-168) - please watch that ticket for progress on that issue.
