### ISSUE TITLE
mixing blocking java driver and async scala driver leads to exception with 1.1.0

### ISSUE THREAD

**Issue by yanns** [mongodb/mongo-scala-driver#8]
I am using the blocking java driver and the non-blocking scala driver to migrate step by step my code to non-blocking IO.
For the moment, I am using the following dependencies:
```
  "org.mongodb" % "mongo-java-driver" % "3.1.1",
  "org.mongodb.scala" %% "mongo-scala-driver" % "1.0.1",
```
and it works well.

By updating the scala driver from **1.0.1** to **1.1.0**:
```
  "org.mongodb" % "mongo-java-driver" % "3.1.1",
  "org.mongodb.scala" %% "mongo-scala-driver" % "1.1.0",
```

I have the following exception at runtime:
```
Caused by: java.lang.NoSuchMethodError: com.mongodb.client.model.FindOptions.getMaxAwaitTime(Ljava/util/concurrent/TimeUnit;)J
	at com.mongodb.async.client.FindIterableImpl.createQueryOperation(FindIterableImpl.java:191) ~[mongodb-driver-async-3.2.0.jar:na]
	at com.mongodb.async.client.FindIterableImpl.execute(FindIterableImpl.java:177) ~[mongodb-driver-async-3.2.0.jar:na]
	at com.mongodb.async.client.FindIterableImpl.batchCursor(FindIterableImpl.java:173) ~[mongodb-driver-async-3.2.0.jar:na]
	at com.mongodb.async.client.MongoIterableSubscription.requestInitialData(MongoIterableSubscription.java:48) ~[mongodb-driver-async-3.2.0.jar:na]
	at com.mongodb.async.client.AbstractSubscription.tryRequestInitialData(AbstractSubscription.java:151) ~[mongodb-driver-async-3.2.0.jar:na]
```

The problem is that the java driver has a copy of some classes that exist also in the `mongodb-driver-core`, leading to confusion at runtime.

Updating the `mongo-java-driver` to `3.2.0` "solves" the problem by having copied of the same classes versions.

I am not sure how to solve this problem in general.
But it'd be good for the mongo drivers ecosystem on the JVM if the dependencies would be better expressed.

**Comment by rozza** [comment]
Hi @yanns,

You're correct in that *1.1.0* - relies on the *3.2.0* series of the Java driver hence the errors.  The dependencies are declared in the [Dependencies.scala](https://github.com/mongodb/mongo-scala-driver/blob/r1.1.0/project/Dependencies.scala#L22) file.

The *mongo-java-driver* is an uber jar you have multiple copies of the same code (see the mongodb-java driver [installation guide](http://mongodb.github.io/mongo-java-driver/3.2/driver/getting-started/installation-guide/)).  As you are using SBT and using it to manage the dependencies, the *mongodb-driver* is a better choice and will allow SBT to inform you of any conflicting versions:

      "org.mongodb" % "mongodb-driver" % "3.2.0",
      "org.mongodb.scala" %% "mongo-scala-driver" % "1.1.0",

I'll endeavour to update the [changelog](http://mongodb.github.io/mongo-scala-driver/1.1/changelog/) to make sure I explicitly mention the Java driver dependency changes going forward.

As this really isn't a actionable issue, the [installation guide](http://mongodb.github.io/mongo-scala-driver/1.1/getting-started/installation-guide/) already identifies the individual dependencies, I'm going to close this issue.  Just to let you know there is the [mongodb-user](http://groups.google.com/group/mongodb-user) mailing list that I also monitor, should you have any further questions.

Happy new year,

Ross

**Comment by yanns** [comment]
Thx, I oversaw that `mongo-java-driver` was an uber jar. From the name, I thought the same king of packaging as the `mongo-scala-driver`.
Thx for all infos, I'll update my build file.
